# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: "gmux"
    binary: gmux
    main: ./cmd/gmux
    ldflags:
      - -s -w -X gmux/lib.Version={{.Version}}


archives:
  - format: tar.gz
    id: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - etc/*
      - LICENSE
      - README.md
      - docs/*

  # - format: binary
  #   id: binary
  #   name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

# brews:
#   - tap:
#       owner: owenthereal
#       name: homebrew-upterm
#     commit_author:
#       name: Owen Ou
#       email: o@owenou.com
#     homepage: https://upterm.dev
#     description: Secure terminal sharing
#     folder: Formula
#     license: "Apache 2.0"
#     custom_block: |
#       head "https://github.com/owenthereal/upterm.git"
#     install: |
#       bin.install "upterm"
#       prefix.install_metafiles
#       bash_completion.install "etc/completion/upterm.bash_completion.sh"
#       zsh_completion.install "etc/completion/upterm.zsh_completion" => "_upterm"
#       man.install "etc/man/man1"
#     test: |
#       assert_match(/Upterm version/, shell_output("#{bin}/upterm version"))
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# brews:
#   - name: gmux

brews:
- name: gmux
  homepage: "https://github.com/corvofeng/gmux"
  repository:
    owner: corvofeng
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_PERSONAL_AUTH_TOKEN }}"


  #  token: ${{ secrets.}}
  # name: gmux
  # description: "A simple port-forward wrapper tool for multiple pods/deployments/services."
  # folder: Formula
  # install: |
  #   bin.install "gmux"
  # test: |
  #   assert_match /A simple port-forward wrapper tool for multiple pods\/deployments\/services/, shell_output("#{bin}/kubepfm -h", 0)
 