# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    id: "kubemux"
    binary: kubemux
    main: ./cmd/kubemux
    ldflags:
      - -s -w -X kubemux/lib.Version={{.Version}}


archives:
  - format: tar.gz
    id: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - etc/*
      - LICENSE
      - README.md
      - docs/*

  # - format: binary
  #   id: binary
  #   name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
- name: kubemux
  homepage: "https://github.com/corvofeng/kubemux"
  repository:
    owner: corvofeng
    name: homebrew-tap
    token: "{{ .Env.HOMEBREW_PERSONAL_AUTH_TOKEN }}"

nfpms: #build:linux
  - license: MIT
    maintainer: corvofeng<corvofeng@gmail.com>
    homepage: "https://github.com/corvofeng/kubemux"
    bindir: /usr
    description: A tmux wrapper like tmuxinator
    file_name_template: '{{ .PackageName }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}{{ with .Mips }}_{{ . }}{{ end }}{{ if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}'
    formats:
      - deb
      - rpm
      - archlinux